# Use postgres/example user/password credentials
version: '3.1'

services:
  estate_postgre:
    image: postgres
    healthcheck:
#      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    ports:
      - 9110:5432
    logging:
      options:
        max-size: 10m
        max-file: "3"
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=estate_management
    volumes:
      - .:/docker-entrypoint-initdb.d/

  estate-adminer:
    image: adminer
    restart: always
    ports:
      - 8484:8080